export const LOGIN_ACTION = 'LOGIN_ACTION'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const HANDLE_DRAWER_ACTION = 'HANDLE_DRAWER_ACTION'

export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'